; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 498
=======
global g_ImportsGameVersion64 := 497
>>>>>>> 722b76646d26b58c4bb7bfa5d1cc4f4830e614c5
global g_ImportsGameVersionPostFix64 := ""